Model:
  version: '2023/9/2'
  srid_org: 4326     #wgs84
  srid_calc: 6677    #平面直角座標9系
  buff_meter: 100    #表示範囲のバッファ（メートル）
  delta_mesh: 10     #表示範囲の補間解像度（メートル）
  sigma_amp: 5000
  lambda: 0.075

  output: F #Trueで出力

  check_surface: True    #Trueで表示
  check_dir : f       #Trueで表示
  check_predict: F #Trueで表示
  check_dmdmode: f #Trueで表示
  show_dmdmode: F #Trueで表示

  


